--
-- DROP DATABASE: TOOLDO
--
-- DROP DATABASE IF EXISTS TOOLDO;

--
-- CREATE DATABASE: TOOLDO
--
-- CREATE DATABASE IF NOT EXISTS TOOLDO;

--
-- CREATE TABLE: RFR_PROFILE
--
CREATE TABLE IF NOT EXISTS RFR_PROFILE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	FIXED CHAR NOT NULL DEFAULT '0',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os profiles ';
--
-- CREATE TABLE: RFR_COURSE
--
CREATE TABLE IF NOT EXISTS RFR_COURSE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED DATE NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os courses';
--
-- CREATE TABLE: RFR_USER
--
CREATE TABLE IF NOT EXISTS RFR_USER
(
	ID INT(10) NOT NULL,
	EMAIL VARCHAR(50) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	PHONENUMBER VARCHAR(20),
	USERNAME VARCHAR(20) NOT NULL,
	PASSWORD VARCHAR(100) NOT NULL,
	CREATED DATE NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	CHANGEPASSWORD CHAR NOT NULL DEFAULT '0',
	FK_RFR_PROFILE INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os users do sistema';

--
-- CREATE INDEX: IDX_RFR_USER_USERNAME
--
CREATE UNIQUE INDEX IDX_RFR_USER_USERNAME ON RFR_USER
(
	USERNAME
);

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_USER_X_RFR_PROFILE
--
ALTER TABLE RFR_USER ADD
	CONSTRAINT FK_RFR_USER_X_RFR_PROFILE FOREIGN KEY (FK_RFR_PROFILE)
		REFERENCES RFR_PROFILE (ID);

--
-- CREATE TABLE: RFR_DISCIPLINE
--
CREATE TABLE IF NOT EXISTS RFR_DISCIPLINE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED DATE NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	FK_RFR_COURSE INT(10) NOT NULL,
	FK_RFR_USER INT(10) COMMENT 'PROFESSOR',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena as disciplines';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_DISCIPLINE_X_RFR_COURSE
--
ALTER TABLE RFR_DISCIPLINE ADD
	CONSTRAINT FK_RFR_DISCIPLINE_X_RFR_COURSE FOREIGN KEY (FK_RFR_COURSE)
		REFERENCES RFR_COURSE (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_DISCIPLINE_X_RFR_USER
--
ALTER TABLE RFR_DISCIPLINE ADD
	CONSTRAINT FK_RFR_DISCIPLINE_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);

--
-- CREATE TABLE: RFR_WORKFLOW_ENTITY
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_ENTITY
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;
--
-- CREATE TABLE: RFR_THEME
--
CREATE TABLE IF NOT EXISTS RFR_THEME
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CSSFILE VARCHAR(50),
	CREATED DATE NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	PUBLISHED CHAR NOT NULL DEFAULT '0',
	PUBLISHCODE INTEGER NULL,
	REPLACEID INT(10) NULL,
	DUPLICATEID INT(10) NULL,
	FK_RFR_DISCIPLINE INT(10) NOT NULL,
	FK_RFR_USER INT(10) NOT NULL COMMENT 'AUTOR',
	FK_RFR_USER_LOCK INT(10) COMMENT 'ID USUÁRIO LOCK',
	FK_RFR_WORKFLOW_ENTITY INT(10),
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os themes';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_THEME_X_FK_RFR_USER_LOCK
--
ALTER TABLE RFR_THEME ADD
	CONSTRAINT FK_RFR_THEME_X_FK_RFR_USER_LOCK FOREIGN KEY (FK_RFR_USER_LOCK)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_THEME_X_RFR_DISCIPLINE
--
ALTER TABLE RFR_THEME ADD
	CONSTRAINT FK_RFR_THEME_X_RFR_DISCIPLINE FOREIGN KEY (FK_RFR_DISCIPLINE)
		REFERENCES RFR_DISCIPLINE (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_THEME_X_RFR_USER
--
ALTER TABLE RFR_THEME ADD
	CONSTRAINT FK_RFR_THEME_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_THEME_X_RFR_WORKFLOW_ENTITY
--
ALTER TABLE RFR_THEME ADD
	CONSTRAINT FK_RFR_THEME_X_RFR_WORKFLOW_ENTITY FOREIGN KEY (FK_RFR_WORKFLOW_ENTITY)
		REFERENCES RFR_WORKFLOW_ENTITY (ID);

--
-- CREATE TABLE: RFR_TOPIC
--
CREATE TABLE IF NOT EXISTS RFR_TOPIC
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED DATE NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	POSITION INT(2) NOT NULL,
	FK_RFR_USER_LOCK INT(10) COMMENT 'ID USUÁRIO LOCK',
	FK_RFR_THEME INT(10) NOT NULL,
	FK_RFR_USER INT(10) NOT NULL COMMENT 'AUTOR',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os topics';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_TOPIC_X_RFR_THEME
--
ALTER TABLE RFR_TOPIC ADD
	CONSTRAINT FK_RFR_TOPIC_X_RFR_THEME FOREIGN KEY (FK_RFR_THEME)
		REFERENCES RFR_THEME (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_TOPIC_X_RFR_USER
--
ALTER TABLE RFR_TOPIC ADD
	CONSTRAINT FK_RFR_TOPIC_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_TOPIC_X_RFR_USER_LOCK
--
ALTER TABLE RFR_TOPIC ADD
	CONSTRAINT FK_RFR_TOPIC_X_RFR_USER_LOCK FOREIGN KEY (FK_RFR_USER_LOCK)
		REFERENCES RFR_USER (ID);

--
-- CREATE TABLE: RFR_PAGE
--
CREATE TABLE IF NOT EXISTS RFR_PAGE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	CREATED DATE NOT NULL,
	POSITION INT(2) NOT NULL,
	ENABLED CHAR NOT NULL DEFAULT '0',
	FK_RFR_TOPIC INT(10) NOT NULL,
	FK_RFR_USER_LOCK INT(10) COMMENT 'ID USUÁRIO LOCK',
	FK_RFR_USER INT(10) NOT NULL COMMENT 'AUTOR',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena as pages';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_PAGE_X_RFR_TOPIC
--
ALTER TABLE RFR_PAGE ADD
	CONSTRAINT FK_RFR_PAGE_X_RFR_TOPIC FOREIGN KEY (FK_RFR_TOPIC)
		REFERENCES RFR_TOPIC (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_PAGE_X_RFR_USER
--
ALTER TABLE RFR_PAGE ADD
	CONSTRAINT FK_RFR_PAGE_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_PAGE_X_RFR_USER_LOCK
--
ALTER TABLE RFR_PAGE ADD
	CONSTRAINT FK_RFR_PAGE_X_RFR_USER_LOCK FOREIGN KEY (FK_RFR_USER_LOCK)
		REFERENCES RFR_USER (ID);

--
-- CREATE TABLE: RFR_ROADMAP_CONTENT
--
CREATE TABLE IF NOT EXISTS RFR_ROADMAP_CONTENT
(
	ID INT(10) NOT NULL,
	ROADMAP TEXT,
	FILE VARCHAR(100),
	FMIME VARCHAR(100),
	FLENGTH BIGINT,
	FDATA LONGBLOB,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os type contents';
--
-- CREATE TABLE: RFR_TYPE_CONTENT
--
CREATE TABLE IF NOT EXISTS RFR_TYPE_CONTENT
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	TYPECONTENT TEXT NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os type contents';
--
-- CREATE TABLE: RFR_CONTENT
--
CREATE TABLE IF NOT EXISTS RFR_CONTENT
(
	ID INT(10) NOT NULL,
	CONTENT TEXT,
	CREATED DATE NOT NULL,
	FK_RFR_PAGE INT(10) NOT NULL,
	FK_RFR_TYPE_CONTENT INT(10) NOT NULL,
	FK_RFR_ROADMAP_CONTENT INT(10),
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena os contents';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_CONTENT_X_RFR_PAGE
--
ALTER TABLE RFR_CONTENT ADD
	CONSTRAINT FK_RFR_CONTENT_X_RFR_PAGE FOREIGN KEY (FK_RFR_PAGE)
		REFERENCES RFR_PAGE (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_CONTENT_X_RFR_ROADMAP_CONTENT
--
ALTER TABLE RFR_CONTENT ADD
	CONSTRAINT FK_RFR_CONTENT_X_RFR_ROADMAP_CONTENT FOREIGN KEY (FK_RFR_ROADMAP_CONTENT)
		REFERENCES RFR_ROADMAP_CONTENT (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_CONTENT_X_RFR_TYPE_CONTENT
--
ALTER TABLE RFR_CONTENT ADD
	CONSTRAINT FK_RFR_CONTENT_X_RFR_TYPE_CONTENT FOREIGN KEY (FK_RFR_TYPE_CONTENT)
		REFERENCES RFR_TYPE_CONTENT (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;

--
-- CREATE TABLE: RFR_WORKFLOW_PHASE_ENTITY
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_PHASE_ENTITY
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	FINISHED CHAR NOT NULL,
	PHASE_ORDER INT(10) NOT NULL,
	FK_RFR_WORKFLOW_ENTITY INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_PHASE_ENTITY_X_RFR_WORKFLOW_ENTITY
--
ALTER TABLE RFR_WORKFLOW_PHASE_ENTITY ADD
	CONSTRAINT FK_RFR_WORKFLOW_PHASE_ENTITY_X_RFR_WORKFLOW_ENTITY FOREIGN KEY (FK_RFR_WORKFLOW_ENTITY)
		REFERENCES RFR_WORKFLOW_ENTITY (ID);

--
-- CREATE TABLE: RFR_WORKFLOW_TEMPLATE
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_TEMPLATE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	ENABLED CHAR NOT NULL DEFAULT '0',
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;
--
-- CREATE TABLE: RFR_QUESTION_CONTENT
--
CREATE TABLE IF NOT EXISTS RFR_QUESTION_CONTENT
(
	ID INT(10) NOT NULL,
	QUESTION TEXT NULL,
	FILE VARCHAR(100),
	FMIME VARCHAR(100),
	FLENGTH BIGINT,
	FDATA LONGBLOB,
	FK_RFR_CONTENT INT(10),
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena question do content';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_QUESTION_CONTENT_X_RFR_CONTENT
--
ALTER TABLE RFR_QUESTION_CONTENT ADD
	CONSTRAINT FK_RFR_QUESTION_CONTENT_X_RFR_CONTENT FOREIGN KEY (FK_RFR_CONTENT)
		REFERENCES RFR_CONTENT (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;

--
-- CREATE TABLE: RFR_ROLE
--
CREATE TABLE IF NOT EXISTS RFR_ROLE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(100) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena as roles do sistema';
--
-- CREATE TABLE: RFR_WORKFLOW_PHASE_TEMPLATE
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_PHASE_TEMPLATE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	PHASE_ORDER INT(10) NOT NULL,
	FK_RFR_WORKFLOW_TEMPLATE INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_PHASE_TEMPLATE_X_RFR_WORKFLOW_TEMPLATE
--
ALTER TABLE RFR_WORKFLOW_PHASE_TEMPLATE ADD
	CONSTRAINT FK_RFR_WORKFLOW_PHASE_TEMPLATE_X_RFR_WORKFLOW_TEMPLATE FOREIGN KEY (FK_RFR_WORKFLOW_TEMPLATE)
		REFERENCES RFR_WORKFLOW_TEMPLATE (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;

--
-- CREATE TABLE: RFR_WORKFLOW_STAGE_ENTITY
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_STAGE_ENTITY
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	FINISHED CHAR DEFAULT '0',
	REQUIRED CHAR NOT NULL,
	FK_RFR_USER INT(10) COMMENT 'USUÁRIO QUE REALIZO O ESTÁGIO',
	FK_RFR_WORKFLOW_PHASE_ENTITY INT(10) NOT NULL,
	FK_RFR_PROFILE INT(10),
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_PROFILE
--
ALTER TABLE RFR_WORKFLOW_STAGE_ENTITY ADD
	CONSTRAINT FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_PROFILE FOREIGN KEY (FK_RFR_PROFILE)
		REFERENCES RFR_PROFILE (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_USER
--
ALTER TABLE RFR_WORKFLOW_STAGE_ENTITY ADD
	CONSTRAINT FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_WORKFLOW_PHASE_ENTITY
--
ALTER TABLE RFR_WORKFLOW_STAGE_ENTITY ADD
	CONSTRAINT FK_RFR_WORKFLOW_STAGE_ENTITY_X_RFR_WORKFLOW_PHASE_ENTITY FOREIGN KEY (FK_RFR_WORKFLOW_PHASE_ENTITY)
		REFERENCES RFR_WORKFLOW_PHASE_ENTITY (ID);

--
-- CREATE TABLE: RFR_ALTERNATIVE_QUESTION
--
CREATE TABLE IF NOT EXISTS RFR_ALTERNATIVE_QUESTION
(
	ID INT(10) NOT NULL,
	ALTERNATIVE VARCHAR(250) NOT NULL,
	COMMENTS VARCHAR(250),
	CORRECT CHAR NOT NULL DEFAULT '0',
	FK_RFR_QUESTION_CONTENT INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_ALTERNATIVE_QUESTION_X_RFR_QUESTION_CONTENT
--
ALTER TABLE RFR_ALTERNATIVE_QUESTION ADD
	CONSTRAINT FK_RFR_ALTERNATIVE_QUESTION_X_RFR_QUESTION_CONTENT FOREIGN KEY (FK_RFR_QUESTION_CONTENT)
		REFERENCES RFR_QUESTION_CONTENT (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;

--
-- CREATE TABLE: RFR_GRANTED_PROFILE_ROLES
--
CREATE TABLE IF NOT EXISTS RFR_GRANTED_PROFILE_ROLES
(
	ID INT(10) NOT NULL,
	FK_RFR_PROFILE INT(10) NOT NULL,
	FK_RFR_ROLE INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena as profile dos user';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_GRANTED_PROFILE_ROLES_X_RFR_PROFILE
--
ALTER TABLE RFR_GRANTED_PROFILE_ROLES ADD
	CONSTRAINT FK_RFR_GRANTED_PROFILE_ROLES_X_RFR_PROFILE FOREIGN KEY (FK_RFR_PROFILE)
		REFERENCES RFR_PROFILE (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_GRANTED_PROFILE_ROLES_X_RFR_ROLE
--
ALTER TABLE RFR_GRANTED_PROFILE_ROLES ADD
	CONSTRAINT FK_RFR_GRANTED_PROFILE_ROLES_X_RFR_ROLE FOREIGN KEY (FK_RFR_ROLE)
		REFERENCES RFR_ROLE (ID)
		ON DELETE RESTRICT
		ON UPDATE RESTRICT;

--
-- CREATE TABLE: RFR_GRANTED_USERS_DISCIPLINE
--
CREATE TABLE IF NOT EXISTS RFR_GRANTED_USERS_DISCIPLINE
(
	ID INT(10) NOT NULL,
	FK_RFR_USER INT(10) NOT NULL,
	FK_RFR_DISCIPLINE INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COMMENT = 'Armazena as discipline dos user';

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_GRANTED_USERS_DISCIPLINE_X_RFR_DISCIPLINE
--
ALTER TABLE RFR_GRANTED_USERS_DISCIPLINE ADD
	CONSTRAINT FK_RFR_GRANTED_USERS_DISCIPLINE_X_RFR_DISCIPLINE FOREIGN KEY (FK_RFR_DISCIPLINE)
		REFERENCES RFR_DISCIPLINE (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_GRANTED_USERS_DISCIPLINE_X_RFR_USER
--
ALTER TABLE RFR_GRANTED_USERS_DISCIPLINE ADD
	CONSTRAINT FK_RFR_GRANTED_USERS_DISCIPLINE_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID)
		ON DELETE CASCADE
		ON UPDATE CASCADE;

--
-- CREATE TABLE: RFR_HISTORY_WORKFLOW_THEME
--
CREATE TABLE IF NOT EXISTS RFR_HISTORY_WORKFLOW_THEME
(
	ID INT(10) NOT NULL,
	CREATED DATE NOT NULL,
	COMMENTS TEXT,
	ACCEPT CHAR NOT NULL DEFAULT '1' COMMENT '1 Aprovado 0 Readequacao',
	FK_RFR_THEME INT(10) NOT NULL,
	FK_RFR_WORKFLOW_STAGE INT(10) NOT NULL,
	FK_RFR_USER INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_THEME
--
ALTER TABLE RFR_HISTORY_WORKFLOW_THEME ADD
	CONSTRAINT FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_THEME FOREIGN KEY (FK_RFR_THEME)
		REFERENCES RFR_THEME (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_USER
--
ALTER TABLE RFR_HISTORY_WORKFLOW_THEME ADD
	CONSTRAINT FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_USER FOREIGN KEY (FK_RFR_USER)
		REFERENCES RFR_USER (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_WORKFLOW_STAGE_CURRENT
--
ALTER TABLE RFR_HISTORY_WORKFLOW_THEME ADD
	CONSTRAINT FK_RFR_HISTORY_WORKFLOW_THEME_X_RFR_WORKFLOW_STAGE_CURRENT FOREIGN KEY (FK_RFR_WORKFLOW_STAGE)
		REFERENCES RFR_WORKFLOW_STAGE_ENTITY (ID);

--
-- CREATE TABLE: RFR_WORKFLOW_STAGE_TEMPLATE
--
CREATE TABLE IF NOT EXISTS RFR_WORKFLOW_STAGE_TEMPLATE
(
	ID INT(10) NOT NULL,
	NAME VARCHAR(100) NOT NULL,
	DESCRIPTION VARCHAR(200),
	REQUIRED CHAR NOT NULL,
	FK_RFR_WORKFLOW_PHASE_TEMPLATE INT(10) NOT NULL,
	FK_RFR_PROFILE INT(10) NOT NULL,
	PRIMARY KEY (ID)
)
	ENGINE = InnoDB
	COLLATE latin1_swedish_ci
	ROW_FORMAT = COMPACT;

--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_STAGE_TEMPLATE_X_RFR_PROFILE
--
ALTER TABLE RFR_WORKFLOW_STAGE_TEMPLATE ADD
	CONSTRAINT FK_RFR_WORKFLOW_STAGE_TEMPLATE_X_RFR_PROFILE FOREIGN KEY (FK_RFR_PROFILE)
		REFERENCES RFR_PROFILE (ID);


--
-- CREATE FOREIGN KEY CONSTRAINT: FK_RFR_WORKFLOW_STAGE_TEMPLATE_X_RFR_WORKFLOW_PHASE_TEMPLATE
--
ALTER TABLE RFR_WORKFLOW_STAGE_TEMPLATE ADD
	CONSTRAINT FK_RFR_WORKFLOW_STAGE_TEMPLATE_X_RFR_WORKFLOW_PHASE_TEMPLATE FOREIGN KEY (FK_RFR_WORKFLOW_PHASE_TEMPLATE)
		REFERENCES RFR_WORKFLOW_PHASE_TEMPLATE (ID);

